# Generated by Django 3.2.4 on 2021-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_student_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='dorm2_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm', models.CharField(max_length=10)),
                ('dorm_number', models.CharField(max_length=10)),
                ('student_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dorm3_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm', models.CharField(max_length=10)),
                ('dorm_number', models.CharField(max_length=10)),
                ('student_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='student_data',
            new_name='dorm1_data',
        ),
    ]
