# Generated by Django 3.2.4 on 2021-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210703_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm1_data',
            name='qr_image',
            field=models.ImageField(null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='dorm2_data',
            name='qr_image',
            field=models.ImageField(null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='dorm3_data',
            name='qr_image',
            field=models.ImageField(null=True, upload_to='qr/'),
        ),
    ]
