# Generated by Django 3.2.4 on 2021-07-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210716_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='chk',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
