# Generated by Django 3.2.4 on 2021-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_uploadfile_chk'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm1_data',
            name='file_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dorm2_data',
            name='file_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dorm3_data',
            name='file_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
