# Generated by Django 3.2.4 on 2021-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_overnight_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overnight_stay',
            name='student_number',
            field=models.IntegerField(),
        ),
    ]
