# Generated by Django 3.2.5 on 2021-07-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_overnight_stay_student_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overnight_stay',
            name='date',
        ),
        migrations.AddField(
            model_name='overnight_stay',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='overnight_stay',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
