# Generated by Django 3.2.5 on 2021-07-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20210729_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overnight_stay',
            name='day',
        ),
        migrations.RemoveField(
            model_name='overnight_stay',
            name='month',
        ),
    ]
