# Generated by Django 3.2.5 on 2021-07-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20210730_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='overnight_stay',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overnight_stay',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
