# Generated by Django 3.2.5 on 2021-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20210730_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='overnight_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.ImageField(upload_to='')),
                ('day', models.ImageField(upload_to='')),
                ('dorm', models.CharField(max_length=10)),
                ('dorm_number', models.CharField(max_length=10)),
            ],
        ),
    ]
