# Generated by Django 3.2.5 on 2021-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_overnight_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overnight_list',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='overnight_list',
            name='month',
            field=models.IntegerField(),
        ),
    ]
