# Generated by Django 3.2.5 on 2021-08-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20210730_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='file/')),
                ('chk', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
